const ON_SEARCH = 'SEARCH/ON_SERACH';
const ON_FILTER = 'FILTER/ON_FILTER';
const SET_FILTER_SUBJ = 'FILTER/SET_FILTER_SUBJ';
const SET_FILTER_GENRE = 'FILTER/SET_FILTER_GENRE';
const SET_FILTER_GRADE = 'FILTER/SET_FILTER_GRADE';
const SEARCH_BY_KEYWORD = 'SEARCH/SEARCH_BY_KEYWORD';
const SET_PRICE = 'UPDATE/SET_PRICE';

export {
    ON_FILTER,
    ON_SEARCH,
    SET_FILTER_SUBJ,
    SET_FILTER_GENRE,
    SET_FILTER_GRADE,
    SEARCH_BY_KEYWORD,
    SET_PRICE
}